# https://www.woolog.dev/backend/docker/database-with-docker/

version: '3'

services:
  chapter6-mysql:
    container_name: chapter6-mysql
    image: mysql
    restart: always
    ports:
      - '3306:3306'
    environment:
      - MYSQL_DATABASE=chapter6_db
      - MYSQL_ROOT_PASSWORD=gopher
      - MYSQL_USER=gopher
      - MYSQL_PASSWORD=gopher
      - TZ=Asia/Seoul
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --lower_case_table_names=1
    volumes:
      - ./mysql:/var/lib/mysql

  chapter6-redis:
    container_name: chapter6-redis
    image: redis
    command: redis-server --port 6379
    restart: always
    labels:
      - name=redis
      - mode=standalone
    ports:
      - '6379:6379'
    volumes:
      - ./redis:/data

  chapter6-mongo:
    container_name: chapter6-mongodb
    image: mongo
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - ./mongo:/data/db
#    environment:
#      - MONGO_INITDB_ROOT_USERNAME=gopher
#      - MONGO_INITDB_ROOT_PASSWORD=gopher
#      - MONGO_INITDB_DATABASE=chapter6