version: '3.8'

services:
  chapter6-mysql:
    container_name: chapter6-mysql
    image: mysql
    restart: always
    ports:
      - '3306:3306'
    environment:
      - MYSQL_DATABASE=chapter6_db
      - MYSQL_ROOT_PASSWORD=gopher
      - MYSQL_USER=gopher
      - MYSQL_PASSWORD=gopher
      - TZ=Asia/Seoul
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --lower_case_table_names=1
    volumes:
      - ./mysql:/var/lib/mysql
